### ISSUE TITLE
[NOTIFIER] - Cannot send a notification with a camera image snapshot

### ISSUE THREAD

**Issue by jmcollin78** [jlpouffier/appdeamon-apps#3]
Hello @jlpouffier ,

I love this component which does exactly what I need.

Recently I buy a camera. There is a link to get a snapshot of this image like this: https://192.168.1.122/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=p1p0b1mb0&user=xxxx&password=xxxx

But I cannot send a notification with this url:

automation.yaml:

```
...
action:
  - event: NOTIFIER
    event_data:
      action: send_to_all
      title: On sonne à la porte
      message: Ca sonne à la porte
      image_url: 'https://192.168.1.122/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=p1p0b1mb0&user=xxxx&password=xxxx'
      click_url: /pieces-2/exterieur
      icon: mdi:bell-ring
      tag: sonnette
      persistent: true
```

Am I missing something ?

Note: it works fine with image_url like `image_url: /media/local/tesla-modele3.png`

**Comment by jlpouffier** [comment]
I think if you are on iOS, the way cameras are supposed to be attached is not exactly the same. 
I do not have a camera but I can look into if if I have time (Do you confirm that you are on iOS?

**Comment by jmcollin78** [comment]
Correct syntaxe is the following: 

```
  - event: NOTIFIER
    event_data:
      action: send_to_all
      title: On sonne à la porte
      message: Ca sonne à la porte
      image_url: /api/camera_proxy/camera.camera_exterieure
      click_url: /pieces-2/exterieur
      icon: mdi:bell-ring
      tag: sonnette
      persistent: true
```

Cf la doc ici : https://companion.home-assistant.io/docs/notifications/dynamic-content
